ClothBazar.Web/ViewModels/ProductViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ClothBazar.Entities;

namespace ClothBazar.Web.ViewModels
{
    public class ProductSearchViewModel
    {
        //public int PageNo { get; set; }
        public List<Product> Products { get; set; }
        public string SearchTerm { get; set; }
        public Pager Pager { get; set; }
    }
    public class NewProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }
        public List<Category> AvailableCategories { get; set; }
    }
    public class EditProductViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }
        public List<Category> AvailableCategories { get; set; }
    }

    public class ProductViewModel
    {
        public Product Product { get; set; }
    }
}

ClothBazar.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClothBazar.Entities;
using ClothBazar.Services;
using ClothBazar.Web.ViewModels;

namespace ClothBazar.Web.Controllers
{
    public class ProductController : Controller
    {

        //ProductsService productsService=new ProductsService();
       // CategoriesService categoryService = new CategoriesService();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductTable(string search, int? pageNo)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();

            model.SearchTerm = search;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var pageSize = ConfigurationsService.Instance.PageSize();

            var totalRecords = ProductsService.Instance.GetAllProductCount(search);
            model.Products = ProductsService.Instance.GetProducts(search, pageNo.Value,pageSize);

            //int pageSize = int.Parse(ConfigurationsService.Instance.GetConfig("ListingPageSize").Value);

            if (model.Products!=null)
            {
                model.Pager = new Pager(totalRecords, pageNo, pageSize);
                return PartialView(model);
            }

            return HttpNotFound();
        }
        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model=new NewProductViewModel();
            model.AvailableCategories = CategoriesService.Instance.GetAllCategories();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
            //CategoriesService categoriesService=new CategoriesService();

            var newProduct=new Product();
            newProduct.Name = model.Name;
            newProduct.Description = model.Description;
            newProduct.Price = model.Price;
            //newProduct.CategoryID = model.CategoryID;
            newProduct.ImageURL = model.ImageURL;
            newProduct.Category = CategoriesService.Instance.GetCategory(model.CategoryID);

            ProductsService.Instance.SaveProduct(newProduct);
            return RedirectToAction("ProductTable");
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();
            var product = ProductsService.Instance.GetProduct(ID);

            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.ImageURL = product.ImageURL;
            model.CategoryID = product.Category != null ? product.Category.ID:0;

            model.AvailableCategories = CategoriesService.Instance.GetAllCategories();

            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            //var existingProduct = productsService.GetProduct(model.ID);
            var existingProduct = ProductsService.Instance.GetProduct(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.Price = model.Price;
            existingProduct.ImageURL = model.ImageURL;
            existingProduct.Category = null;// CategoriesService.Instance.GetCategory(model.CategoryID);
            existingProduct.CategoryID = model.CategoryID;

            if (!string.IsNullOrEmpty(model.ImageURL))
            {
                existingProduct.ImageURL = model.ImageURL;
            }

            //productsService.UpdateProduct(existingProduct);

            ProductsService.Instance.UpdateProduct(existingProduct);
            return RedirectToAction("ProductTable");
        }
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductsService.Instance.DeleteProduct(ID);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int ID)
        {
            ProductViewModel model = new ProductViewModel();
            model.Product = ProductsService.Instance.GetProduct(ID); 

            if (model.Product==null) { return HttpNotFound(); }

            return View(model);
        }
    
    }
}

ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };

                //var newImage = new Image() { Name = fileName };

                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

ClothBazar.Web/Views/Product/Create.cshtml
@model NewProductViewModel
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/system/placeholder-image.png";
}

<form id="createProduct">
    <div class="row">
                <div class="col-md-8">
                <div class="form-group">
                    <label>Category</label>
                    <select class="form-control" name="CategoryID">
                        @foreach (var category in Model.AvailableCategories)
                        {
                            <option value="@category.ID">@category.Name</option>
                        }
                    </select>

                </div>
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name"/>
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input class="form-control" name="Description"/>
                </div>
                <div class="form-group">
                    <label>Price</label>
                    <input class="form-control" name="Price"/>
                </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div>
                    <br />
                    <label>Image</label>
                    <input id="ImageURL" name="ImageURL" type="hidden" />
                    <input id="imageUpload" name="Image" type="file" accept=".png,.jpg" />
                    <br/>
                <button id="saveBtn" type="button" class="btn btn-primary">Submit</button>
                <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
                </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />
            </div>
        </div>
    </div>
</form>

<script>
    $('#createProduct').validate({
        rules: {
            Name: {
                required: true,
                minlength: 5,
                maxlength: 50,
            },
            Description: {
                maxlength: 500
            },
            Price: {
                range: [1, 100000]
            }
        },
        messages: {
            Name: {
                required: 'Name is required',
                minlength: 'Minimum Length is 5',
                maxlength: 'Maximum Length is 50'
            },
            Description: {
                maxlength: 'Maximum Length is 500'
            },
            Price: {
                range: 'Price must be within range of 1 - 100000.'
            }
        }
    });


    $("#imageUpload").change(function () {
        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
                type: 'POST',
                url: '@Url.Action("UploadImage", "Shared")',
                dataType: 'json',
                data: formData,
                contentType: false,
                processData: false
            })
            .done(function(response) {
                console.log(response);
                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#productImage").attr("src", response.ImageURL);
                }
            })
            .fail(function(XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
    $("#saveBtn").click(function() {
        if ($("#createProduct").valid())
        {
            $.ajax({
                    type: "POST",
                    url: '@Url.Action("Create", "Product")',
                data: $("#createProduct").serialize()

            })
            .done(function (response) {
                $("#tableContainer").html(response),
                    $("#actionTable").html("");
                focusAction("tableContainer");
            })
            .fail(function (xmlHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
        }
        else {
            swal({
                title: "Warning",
                text: "Please enter all valid data in fields.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            });
        }
        });

    $("#cancelBtn").click(function () {
        $("#actionTable").html("");
        focusAction("tableContainer");
    });
</script>

ClothBazar.Web/Views/Product/Edit.cshtml
@model EditProductViewModel

@{
    ViewBag.Title = "Edit";
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/system/placeholder-image.png";

}



<form id="editProduct">

    <h2>Edit product</h2>
    <div class="row">
            <div class="col-md-8">
                    <input name="ID"value="@Model.ID" type="hidden"/>

                    <label>Category</label>
                    <select class="form-control" name="CategoryID">
                        @foreach (var category in Model.AvailableCategories)
                        {
                            var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                            <option value="@category.ID" @selected>@category.Name</option>
                        }
                    </select>

                    <label>Name</label>
                    <input name="Name" value="@Model.Name"/>
                    <br/>
                    <label>Description</label>
                    <input name="Description"value="@Model.Description"/>
                    <br/>
                    <label>Price</label>
                    <input name="Price"value="@Model.Price"/>
                    <br />
                    <label>Image</label>
                    <input id="ImageURL" name="ImageURL" type="hidden" />
                    <input id="imageUpload" name="Image" type="file" accept=".png,.jpg" />
                    <br/>
                    <button id="updateBtn" type="button">Update</button>
                    <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
            </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" src="@imageURL" id="categoryImage"value="@Model.ImageURL" />
            </div>
        </div>
        
    </div>

   

</form>
<script>
    $('#editProduct').validate({
        rules: {
            Name: {
                required: true,
                minlength: 5,
                maxlength: 50,
            },
            Description: {
                maxlength: 500
            },
            Price: {
                range: [1, 100000]
            }
        },
        messages: {
            Name: {
                required: 'Name is required',
                minlength: 'Minimum Length is 5',
                maxlength: 'Maximum Length is 50'
            },
            Description: {
                maxlength: 'Maximum Length is 500'
            },
            Price: {
                range: 'Price must be within range of 1 - 100000.'
            }
        }
    });

    $("#imageUpload").change(function () {
        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
                type: 'POST',
                url: '@Url.Action("UploadImage", "Shared")',
                dataType: 'json',
                data: formData,
                contentType: false,
                processData: false
            })
            .done(function(response) {
                console.log(response);
                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#productImage").attr("src", response.ImageURL);
                }
            })
            .fail(function(XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });

    $("#updateBtn").click(function() {
        if ($("#editProduct").valid())
        {
            $.ajax({
                    type: "POST",
                    url: '@Url.Action("Edit", "Product")',
                data: $("#editProduct").serialize()

            })
            .done(function (response) {
                $("#tableContainer").html(response),
                    $("#actionTable").html("");
                focusAction("tableContiner");
            })
            .fail(function (xmlHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
        }
        else {
            swal({
                title: "Warning",
                text: "Please enter all valid data in fields.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            });
        }

    });
    $("#cancelBtn").click(function () {
        $("#actionTable").html("");
        focusAction("tableContiner");
    });
</script>

ClothBazar.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Products";
}
<div class="container">
    <div id="tableContainer">
        @{
            Html.RenderAction("ProductTable");
        }


    </div>

    <hr/>
    <div id="actionTable">
    
    </div>
</div>
<script>
    function focusAction(controlToFocus) {
        $('html, body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
</script> 

ClothBazar.Web/Views/Product/ProductTable.cshtml
@model ClothBazar.Web.ViewModels.ProductSearchViewModel
@{
    ViewBag.Title = "ProductTable";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>

<div>
    <form method="post">
        <input id="searchTxt" value="@Model.SearchTerm" name="Search">
        <button type="button" id="searchBtn"><i class="fa fa-search"></i></button>
   
    @*<form method="post">
            <input id="searchTxt" name="Search"/>
            <button type="button"id="searchBtn">Search</button>
        </form>*@
    <button type="button" id="newBtn">New</button>
    <button  type="button" id="resetBtn">Reset</button>
    </form>
</div>

<div id="tableContainer">
    <table  id="ProductsTable" class="table table-striped">
        <thead>
        <tr>
            <td>Product Name</td>
            <td>Category</td>
            <td>Price</td>
            <td class="wrap-td">Actions</td>
        </tr>
        </thead>
        <tbody>
        @if (Model.Products != null && Model.Products.Count > 0)
        {
            foreach (var product in Model.Products)
            {
                <tr>
                    <td>@product.Name</td>
                    <td>
                        @if (product.Category != null)
                        {
                            <text>@product.Category.Name</text>
                        }
                        else
                        {
                            <text>-</text>
                        }
                    </td>
                    <td>@product.Price</td>
                    <td class="wrap-td">
                        <button class="editBtn" data-id="@product.ID">Edit</button>
                        <button class="deleteBtn" data-id="@product.ID">Delete</button>
                        <button class="addtoCart" data-id="@product.ID">Add To Cart</button>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td class="text-danger" colspan="4">No Products found.</td>
               
               
    
            </tr>
        }
        </tbody>
    </table>
    <div>
        @if (Model.Pager != null&& Model.Pager.TotalPages>1)
        {

            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageno="1">First</button>
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</button>
            }

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <button class="@activeClass pageButtons" data-pageno="@page">@page</button>
            }

            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</button>
                <button class="pageButtons" data-pageno="@Model.Pager.EndPage">Last</button>
            }			
        }
    </div>
</div>
<script>


    $(".pageButtons").click(function () {
        $.ajax({
            url: '@Url.Action("ProductTable", "Product")',
                data: {
                    pageNo: $(this).attr("data-pageno"),
                    search: '@Model.SearchTerm'
                }
            })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();
        $.ajax({
                url: '@Url.Action("ProductTable", "Product")',
                data: {
                    search: searchValue
                }

            })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (xmlHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });

    });

    $("#resetBtn").click(function () {
        var searchValue = '';

        $.ajax({
                url: '@Url.Action("ProductTable", "Product")',
                data: {

                    search: searchValue
                }
            })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
    $("#newBtn").click(function () {

        $.ajax({

                url: '@Url.Action("Create", "Product")'


            })
            .done(function (response) {
                $("#actionTable").html(response);
                focusAction("actionTable");
            })
            .fail(function (xmlHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });

    });
    $(".editBtn").click(function () {

        $.ajax({
                url: '@Url.Action("Edit", "Product")',
                data: {
                    Id: $(this).attr('data-id')
                }

            })
            .done(function (response) {
                $("#actionTable").html(response);
                focusAction("actionTable");
            })
            .fail(function (xmlHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });

    });
    $(".deleteBtn").click(function () {

        Swal.fire({
                title: 'Confirm',
                text: "Do your want to delete the data",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            })
            .then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                            type: 'POST',
                            url: '@Url.Action("Delete", "Product")',
                            data: {
                                Id: $(this).attr('data-id')
                            }

                        })
                        .done(function (response) {
                            $("#tableContainer").html(response);
                            Swal.fire(
                                'Deleted!',
                                'Your file has been deleted.',
                                'success'
                            )
                        })
                        .fail(function (xmlHttpRequest, textStatus, errorThrown) {
                            alert("Fail");
                        });


                }
            })
    });

    var products = [];
    $(".add-to-cart").click(function () {
        var productID = $(this).attr('data-id');

        products.push(productID);
        $.cookie('CartProducts', products.join("-"), { expires: 7, path: '/' });
        alert("cookieValue");
    });
</script>