ClothBazar.Web/ViewModels/CategoryViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ClothBazar.Entities;

namespace ClothBazar.Web.ViewModels
{
    public class NewCategoryViewModels
    {
        [Required]
        [MinLength(5), MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }

        public decimal Price { get; set; }
        public string ImageURL { get; set; }


        public int CategoryID { get; set; }
        public bool isFeatured { get; set; }
    }

    public class CategorySearchViewModel
    {
        public List<Category> Categories { get; set; }
        public string SearchTerm { get; set; }
        public Pager Pager { get; set; }
    }

    public class EditCategoryViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }

        public string ImageURL { get; set; }

        public bool isFeatured { get; set; }
    }
}

ClothBazar.Web/Controllers/CategoryController.cs
using ClothBazar.Entities;
using ClothBazar.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClothBazar.Web.ViewModels;

namespace ClothBazar.Web.Controllers
{
    public class CategoryController : Controller
    {
        //CategoriesService categoriesService= new CategoriesService();

        public ActionResult Index()
        {
            

            return View();
        }
        public ActionResult CategoryTable(string search,int? pageNo)
        {
            CategorySearchViewModel model=new CategorySearchViewModel();
            model.SearchTerm = search;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var totalRecords = CategoriesService.Instance.GetCategoriesCount(search);
            model.Categories = CategoriesService.Instance.GetCategories(search, pageNo.Value);

            int pageSize = int.Parse(ConfigurationsService.Instance.GetConfig("ListingPageSize").Value);

            if (model.Categories!=null)
            {
                model.Pager = new Pager(totalRecords, pageNo, pageSize);
                return PartialView(model);
            }

            return HttpNotFound();
        }

        [HttpGet]
        public ActionResult Create()
        {
            NewCategoryViewModels model=new NewCategoryViewModels();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Create(NewCategoryViewModels model)
        {


            //categoryService.SaveCategory(category);
            if(ModelState.IsValid)
            {
                var newCategory = new Category();
                newCategory.Name = model.Name;
                newCategory.Description = model.Description;
                newCategory.ImageURL = model.ImageURL;
                newCategory.isFeatured = model.isFeatured;

                CategoriesService.Instance.SaveCategory(newCategory);

                return RedirectToAction("CategoryTable");
            }

            return new HttpStatusCodeResult(500);
            
            
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditCategoryViewModel model=new EditCategoryViewModel();
            var category = CategoriesService.Instance.GetCategory(ID);

            model.ID = category.ID;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageURL;
            model.isFeatured = category.isFeatured;

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel model)
        {
            var existingCategory = CategoriesService.Instance.GetCategory(model.ID);
            existingCategory.Name = model.Name;
            existingCategory.Description = model.Description;
            existingCategory.ImageURL = model.ImageURL;
            existingCategory.isFeatured = model.isFeatured;

            CategoriesService.Instance.UpdateCategory(existingCategory);
            return RedirectToAction("CategoryTable");
        }
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            CategoriesService.Instance.DeleteCategory(ID);
            return RedirectToAction("CategoryTable");
        }


    }
}

ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };

                //var newImage = new Image() { Name = fileName };

                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

ClothBazar.Web/Views/Category/CategoryTable.cshtml
@model ClothBazar.Web.ViewModels.CategorySearchViewModel
@{
    ViewBag.Title = "CategoryTable";
}

<h2>CategoryTable</h2>
<div>
    <form method="post">

        <input id="searchTxt" value="@Model.SearchTerm" name="Search">
        <button type="button" id="searchBtn"><i class="fa fa-search"></i></button>
    </form>
    @*<form method="post">
            <input id="searchTxt" name="Search"/>
            <button type="button"id="searchBtn">Search</button>
        </form>*@
    <button type="button" id="newBtn">New</button>
    <button type="button" id="resetBtn">Reset</button>
</div>
<div id="tableContainer">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Category Name</th>
                <th>Products</th>
                <th>Actions</th>

            </tr>
        </thead>
        <tbody>
            @if (Model.Categories != null && Model.Categories.Count > 0)
            {
                foreach (var category in Model.Categories)
                {
                    <tr>
                        <td>@category.Name</td>
                        <td>
                            @category.Products.Count
                        </td>

                        <td>
                            <button class="editBtn" data-id="@category.ID">Edit</button>
                            <button class="deleteBtn" data-id="@category.ID">Delete</button>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div>
        @if (Model.Pager != null&& Model.Pager.TotalPages>1)
        {

            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageno="1">First</button>
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</button>
            }

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <button class="@activeClass pageButtons" data-pageno="@page">@page</button>
            }

            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</button>
                <button class="pageButtons" data-pageno="@Model.Pager.EndPage">Last</button>
            }
        }
    </div>
</div>

<script>
    $(".pageButtons").click(function () {
        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',
            data: {
                pageNo: $(this).attr("data-pageNo"),
                search: '@Model.SearchTerm'

            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();

        $.ajax({
            url: '@Url.Action("CategoryTable","Category")',
            data: {
                search: searchValue
            }
        }).done(function (response) {
            $("#tableContainer").html(response);
        }).fail(function (xmlHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        });

    });
    $("#resetBtn").click(function () {
        var searchValue = '';

        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',//'/Category/CategoryTable',
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
    $("#newBtn").click(function () {

        $.ajax({
            url: '@Url.Action("Create","Category")',


        }).done(function (response) {
            $("#actionTable").html(response);
            focusAction("actionTable");
        }).fail(function (xmlHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        });

    });
    $(".editBtn").click(function () {

        $.ajax({
            url: '@Url.Action("Edit","Category")',
            data: {
                Id: $(this).attr('data-id')
            }

        }).done(function (response) {
            $("#actionTable").html(response);
            focusAction("actionTable");
        }).fail(function (xmlHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        });

    });
    $(".deleteBtn").click(function() {
        var confirmDelete = confirm("Do your want to delete the data ?");
        if (confirmDelete) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Delete","Category")',
                data: {
                    Id: $(this).attr('data-ID')
                }
            }).done(function(response) {
                $("#tableContainer").html(response);
            }).fail(function(xmlHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
        }
    });



</script>

ClothBazar.Web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<form id="createCategory">
    <div class="row">
        <div class="col-md-8">
            <label>Name</label>
            <input name="Name" />
            <br />
            <label>Description</label>
            <input name="Description" />
            <br />
            <label>Image</label>
            <input id="ImageURL" name="ImageURL" type="hidden" />
            <input id="imageUpload" name="Image" type="file" accept=".png,.jpg" />

            <br />
            <label>Is Featured ?</label>
            <input name="isFeatured" type="radio" value="True" />True
            <input name="isFeatured" type="radio" value="False" />False
            <br />

            <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
            <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>

        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="categoryImage" />
            </div>
        </div>
    </div>


</form>
<script>
    $("#imageUpload").change(function () {
        var element = this;

        var formData = new FormData();

        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (response) {
                console.log(response);

                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#categoryImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
    $("#createCategory").validate({
        rules: {
            Name: {
                required: true,
                minlength: 5,
                maxlength: 50
            },
            Description: {
                maxlength: 500
            }
        },
        messages: {
            Name: {
                required: 'Name is required!',
                minlength: 'Minimum Length is 5',
                maxlength: 'Maximum Length is 50'
            },
            Description: {
                maxlength: 'Maximum Length is 500'
            }
        }
    });

    $("#saveBtn").click(function () {
        if ($("#createCategory").valid()) {

            $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "Category")',
                data: $("#createCategory").serialize()


            })
                .done(function (response) {
                    $("#tableContainer").html(response),
                        $("#actionTable").html("");
                    focusAction("tableContainer");
                })
                .fail(function (xmlHttpRequest, textStatus, errorThrown) {
                    swal({
                        title: "Warning",
                        text: "Please enter all required fields.",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true
                    });
                });
        }
        else {
            swal({
                title: "JS Warning",
                text: "Please enter all required fields.",
                icon: "warning",
                buttons: true,
                dangerMode: true
            });

        }
    });




    $("#cancelBtn").click(function () {
        $("#actionTable").html("");
        focusAction("tableContainer");
    });
</script>

ClothBazar.Web/Views/Category/Delete.cshtml
@model ClothBazar.Entities.Category
@{
    ViewBag.Title = "Delete";
}

<h2>Delete Category</h2>
<h3>Do you want to delete!?</h3>
<form method="post">
    <input type="hidden" name="ID" value="@Model.ID" />
    <button type="submit">Delete</button>

</form>
<h3>@Html.ActionLink("Cancel", "Index")</h3>

ClothBazar.Web/Views/Category/Edit.cshtml
@model ClothBazar.Web.ViewModels.EditCategoryViewModel
@{
    ViewBag.Title = "Edit";
    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/system/placeholder-image.png";
}

<h2>Edit Category</h2>

<form id="editCategory">
    <div class="row">
        <div class="col-md-8">
            <input type="hidden"name="ID"value="@Model.ID"/>
            <label>Name</label>
            <input name="Name" value="@Model.Name"/>
            <br/>
            <label>Description</label>
            <input name="Description"value="@Model.Description"/>
            <br/>
            <label>Image</label>
            <input id="ImageURL" name="ImageURL" type="hidden"value="@Model.ImageURL"/>
            <input id="imageUpload" name="Image" type="file" accept=".png,.jpg"/>

            <br/>
            <label>Is Featured ?</label>
            <input name="isFeatured" type="radio" value="True"@trueChecked/>True
            <input name="isFeatured" type="radio" value="False" @falseChecked/>False
            <br/>
        </div>
            <div class="col-md-4">
                <div class="thumb">
                    <img class="img-thumbnail img-fluid" src="@imageURL" id="categoryImage"value="@Model.ImageURL" />
                </div>
            </div>
        
    </div>


    <button id="updateBtn" type="button">Update</button>
    <button id="cancelBtn" type="button">Cancel</button>

</form>
<script>
    $("#imageUpload").change(function () {
        var element = this;

        var formData = new FormData();

        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
                type: 'POST',
                url: '@Url.Action("UploadImage", "Shared")',
                dataType: 'json',
                data: formData,
                contentType: false,
                processData: false
            })
            .done(function (response) {
                console.log(response);

                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#categoryImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });

    $("#updateBtn").click(function() {

        $.ajax({
                type: "POST",
                url: '@Url.Action("Edit", "Category")',
                data: $("#editCategory").serialize()
            })
            .done(function(response) {
                $("#tableContainer").html(response),
                    $("#actionTable").html("");
                focusAction("tableContiner");
            })
            .fail(function(xmlHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#cancelBtn").click(function () {
        $("#actionTable").html("");
        focusAction("tableContiner");
    });

</script>

ClothBazar.Web/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Categories";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>

<div class="container">
    <div id="tableContainer">
        @{
            Html.RenderAction("CategoryTable");
        }


    </div>

    <hr />
    <div id="actionTable">

    </div>
</div>
<script>
    function focusAction(controlToFocus) {
        $('html, body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
</script>